source "http://rubygems.org"

gem "selenium-webdriver"
gem "cucumber"
gem "rspec"
gem "capybara"
gem "pry"
gem "poltergeist"
gem "report_builder"
gem "ffaker"
gem "httparty", "0.17.0"
gem "activesupport", "6.0.0"
gem "crack", "0.4.3"
gem "log4r"
gem "fileutils", "1.4.1"
